version: '3.4'

services:
  demousersaveapi:
    image: ${DOCKER_REGISTRY-}demousersaveapi
    environment:
      - EMULATOR_HOST=datastore
      - PROJECT_ID=project-test
      - DATASTOREDB_HOST=datastore
      - DATASTOREDB_PROJECT=project-test
      - DATASTOREDB_PORT=8081
    build:
      context: .
      dockerfile: DemoUserSaveAPI/Dockerfile
    depends_on:
      - datastore

  #firestore:
   # image: perrystallings/cloud-firestore-emulator
    #environment:
     # - FIRESTORE_PROJECT_ID=project-test

  datastore:
    image: singularities/datastore-emulator
    environment:
      - DATASTORE_PROJECT_ID=project-test
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081

